"""Declared capability partition for the Finalis 1000 Architecture Twin.

This is the DECLARED intent (SP0001 D-0001-02): the human-curated map of which
paths / routes / tables / permissions each protected capability owns, and the
allowed/forbidden dependency contracts. It is grounded in AUDIT_TRACE_1_MASTER
and SP0000. `bootstrap.py` renders this into FINALIS_1000_ARCHITECTURE_TWIN.json;
the observer produces the OBSERVED twin from code; conformance compares them.

Ownership is by longest-prefix path match, so a nested capability (e.g. B9.1
recovery tables `ai_local_transaction_recovery_`) wins over its parent
(`ai_local_transaction`). Every product module under finalis/ must map to
exactly one capability (INV-0001-01).
"""
from __future__ import annotations

DNR = "DO_NOT_REBUILD"

# Common allowed low-level dependencies every capability may import.
_BASE = ["finalis.audit", "finalis.models"]

# capability_id -> spec
CAPABILITIES: list[dict] = [
    # ---- product engines (Layer 0) ----
    {"id": "crm", "owner": "finalis/crm", "classification": "product_engine",
     "purpose": "Relationship Core CRM — own-IP case-first system of record for parties/relationships.",
     "paths": ["finalis/crm/", "finalis/portal/crm_store.py"],
     "routes": ["/crm"], "tables": ["crm_", "parties"], "perms": ["crm"],
     "forbidden": ["finalis.ai_employee"]},
    {"id": "evidence", "owner": "finalis/evidence", "classification": "product_engine",
     "purpose": "Evidence Trust Fabric — objects, chain, contracts, holds, merkle transparency log, proof reports.",
     "paths": ["finalis/evidence/", "finalis/portal/evidence_store.py", "finalis/documents.py"],
     "routes": ["/evidence", "/upload-links"], "tables": ["evidence_", "documents", "upload_links"],
     "perms": ["evidence", "document"], "forbidden": ["finalis.ai_employee"]},
    {"id": "case_graph", "owner": "finalis/case_services.py", "classification": "product_engine",
     "purpose": "Case Graph — case structure, missing-info, promises, NBA, action gate, completion loop.",
     "paths": ["finalis/case_services.py", "finalis/completion_loop.py"],
     "routes": ["/cases", "/completion-loop"],
     "tables": ["cases", "missing_items", "promises", "transcripts"],
     "perms": ["case"], "forbidden": ["finalis.ai_employee"]},
    {"id": "lifecycle_universal", "owner": "finalis/lifecycle", "classification": "product_engine",
     "purpose": "Universal lifecycle logic — LifecycleVector, completion rule, outcome invariants, scoring, evidence bundles.",
     "paths": ["finalis/lifecycle/"], "routes": [], "tables": [],
     "perms": [], "forbidden": ["finalis.ai_employee"]},
    {"id": "cpq", "owner": "finalis/quotes", "classification": "product_engine",
     "purpose": "CPQ / Quote Builder — Decimal pricing, approvals, change orders (mock payment/PDF/e-sign).",
     "paths": ["finalis/quotes/", "finalis/portal/quote_store.py"],
     "routes": ["/quotes", "/price-books", "/pricing-rules", "/pricing", "/offers"],
     "tables": ["quotes", "quote_", "price_book", "price_books", "pricing_rules",
                "change_orders", "acceptance_evidence", "payment_requirements", "offers"],
     "perms": ["quote", "pricing"], "forbidden": ["finalis.ai_employee"]},
    {"id": "scheduling", "owner": "finalis/scheduling", "classification": "product_engine",
     "purpose": "Calendar & Scheduling — appointment types, availability, confirmation tokens (mock calendar/video).",
     "paths": ["finalis/scheduling/", "finalis/portal/scheduling_store.py"],
     "routes": ["/scheduling"], "tables": ["scheduling_"], "perms": ["scheduling"],
     "forbidden": ["finalis.ai_employee"]},
    {"id": "telephony", "owner": "finalis/telephony", "classification": "product_engine",
     "purpose": "Telephony & Call Control — mock provider, permission gate, consent, dispositions, retry.",
     "paths": ["finalis/telephony/"], "routes": ["/telephony"], "tables": ["call_sessions"],
     "perms": ["telephony", "call"], "forbidden": ["finalis.ai_employee"]},
    {"id": "voice", "owner": "finalis/voice", "classification": "product_engine",
     "purpose": "Voice Engine + Conversation Intelligence — gateway, ASR/TTS routers (mock seams), understanding, dialogue.",
     "paths": ["finalis/voice/", "finalis/ocr_router.py", "finalis/webscout.py"],
     "routes": [], "tables": [], "perms": ["voice"], "forbidden": ["finalis.ai_employee"]},
    {"id": "action_communication", "owner": "finalis/actions", "classification": "product_engine",
     "purpose": "Action & Communication — gate/consent/rate-limit/route/compose/approve/schedule/send/track (mock delivery).",
     "paths": ["finalis/actions/"], "routes": ["/actions"],
     "tables": ["action_requests", "message_drafts", "executions", "delivery_events"],
     "perms": ["action"], "forbidden": ["finalis.ai_employee"]},
    {"id": "command_center", "owner": "finalis/dashboard.py", "classification": "product_engine",
     "purpose": "Case Command Center — dashboard service + server-rendered view.",
     "paths": ["finalis/dashboard.py", "finalis/dashboard_html.py"],
     "routes": ["/dashboard"], "tables": [], "perms": ["dashboard"],
     "forbidden": ["finalis.ai_employee"]},
    {"id": "agent_runtime_governance", "owner": "finalis/governance", "classification": "product_engine",
     "purpose": "Agent Runtime Governance & Observability — trace redaction, policy gate, budgets, scores, flags, autonomy, scoring, state machine.",
     "paths": ["finalis/governance/", "finalis/autonomy.py", "finalis/certainty_core.py",
               "finalis/scoring.py", "finalis/state_machine.py"],
     "routes": ["/governance"], "tables": [], "perms": ["governance", "access_log"],
     "forbidden": []},
    {"id": "audit_chain", "owner": "finalis/audit.py", "classification": "cross_cutting",
     "purpose": "Tamper-evident hash-chained audit log.",
     "paths": ["finalis/audit.py"], "routes": ["/audit"], "tables": ["audit_events"],
     "perms": ["audit"], "forbidden": []},
    {"id": "rbac_admin", "owner": "finalis/admin", "classification": "cross_cutting",
     "purpose": "Admin/Tenant/User/RBAC control plane — 9 roles, 45 permissions, deny-by-default, tenant isolation, hashed keys.",
     "paths": ["finalis/admin/", "finalis/portal/auth.py"],
     "routes": ["/admin", "/auth"], "tables": ["users", "tenants"],
     "perms": ["rbac", "admin", "user", "tenant", "auth", "ai"], "forbidden": []},
    {"id": "portal_shell", "owner": "finalis/portal/app.py", "classification": "presentation",
     "purpose": "FastAPI app + server-rendered UI + SQLite migrations. PRESENTATION — never business authority (INV-0001-11).",
     "paths": ["finalis/portal/app.py", "finalis/portal/ui.py", "finalis/portal/db.py",
               "finalis/portal/seed.py", "finalis/portal/serve.py", "finalis/portal/store.py",
               "finalis/portal/__init__.py", "finalis/models.py", "finalis/__init__.py"],
     "routes": ["/confirm", "/"], "tables": ["schema_version"], "perms": [],
     "forbidden": []},

    # ---- CORE governance ladder ----
    {"id": "core_a1_identity", "owner": "finalis/ai_employee/identity.py", "classification": "governance_core",
     "purpose": "CORE-A1 AI Employee identity + authority boundary.",
     "paths": ["finalis/ai_employee/identity.py", "finalis/ai_employee/authority.py",
               "finalis/ai_employee/store.py"],
     "routes": ["/ai-employees"], "tables": ["ai_employees"], "perms": ["ai_employee"],
     "forbidden": []},
    {"id": "core_a2_tasks", "owner": "finalis/ai_employee/tasks.py", "classification": "governance_core",
     "purpose": "CORE-A2 Secure Work Intake Registry + Canonical Task Contract.",
     "paths": ["finalis/ai_employee/tasks.py", "finalis/ai_employee/task_store.py"],
     "routes": ["/ai-tasks"], "tables": ["ai_tasks", "ai_task_intake_events", "ai_task_transitions"],
     "perms": ["ai_task"], "forbidden": []},
    {"id": "core_a3_run_ledger", "owner": "finalis/ai_employee/run_ledger.py", "classification": "governance_core",
     "purpose": "CORE-A3 Causally Verifiable Run Ledger + Event-Sourced Replay.",
     "paths": ["finalis/ai_employee/run_ledger.py", "finalis/ai_employee/run_store.py"],
     "routes": ["/ai-runs"], "tables": ["ai_runs", "ai_run_events"], "perms": ["ai_run"],
     "forbidden": []},
    {"id": "core_a4_approvals", "owner": "finalis/ai_employee/approvals.py", "classification": "governance_core",
     "purpose": "CORE-A4 Human Approval Gate + non-transferable grants.",
     "paths": ["finalis/ai_employee/approvals.py", "finalis/ai_employee/approval_decisions.py",
               "finalis/ai_employee/approval_store.py"],
     "routes": ["/ai-approvals"], "tables": ["ai_approval_"], "perms": ["ai_approval"],
     "forbidden": []},
    {"id": "core_a5_lifecycle", "owner": "finalis/ai_employee/lifecycle.py", "classification": "governance_core",
     "purpose": "CORE-A5 Deterministic Lifecycle Kernel + Completion Loop.",
     "paths": ["finalis/ai_employee/lifecycle.py", "finalis/ai_employee/lifecycle_store.py"],
     "routes": [], "tables": [], "perms": [], "forbidden": []},
    {"id": "core_a6_artifacts", "owner": "finalis/ai_employee/artifacts.py", "classification": "governance_core",
     "purpose": "CORE-A6 Evidence-Grade Artifact System + Claim Graph + Materialization Firewall.",
     "paths": ["finalis/ai_employee/artifacts.py", "finalis/ai_employee/artifact_store.py"],
     "routes": ["/ai-artifacts"], "tables": ["ai_artifacts", "ai_artifact_versions"],
     "perms": ["ai_artifact"], "forbidden": []},

    # ---- TOOL governance ladder ----
    {"id": "tool_b1_registry", "owner": "finalis/ai_employee/tool_registry.py", "classification": "governance_tool",
     "purpose": "TOOL-B1 Zero-Trust Tool Capability Governance Registry + Admission Firewall.",
     "paths": ["finalis/ai_employee/tool_registry.py", "finalis/ai_employee/tool_registry_store.py"],
     "routes": ["/ai-tools/registry", "/ai-tools/{tool_id}", "/ai-tools"],
     "tables": ["ai_tools", "ai_tool_versions", "ai_tool_registry_events"],
     "perms": ["ai_tool"], "forbidden": []},
    {"id": "tool_b2_quality", "owner": "finalis/ai_employee/tool_quality.py", "classification": "governance_tool",
     "purpose": "TOOL-B2 Formal Tool Descriptor Assurance Graph + Planner Selection Boundary.",
     "paths": ["finalis/ai_employee/tool_quality.py", "finalis/ai_employee/tool_quality_store.py"],
     "routes": ["/ai-tools/quality"], "tables": ["ai_tool_quality_"], "perms": [], "forbidden": []},
    {"id": "tool_b3_contracts", "owner": "finalis/ai_employee/tool_contracts.py", "classification": "governance_tool",
     "purpose": "TOOL-B3 Formal Protocol Contract Proof Kernel (targets are *_LIKE shapes, not real runtime).",
     "paths": ["finalis/ai_employee/tool_contracts.py", "finalis/ai_employee/tool_contracts_store.py"],
     "routes": ["/ai-tools/contracts"], "tables": ["ai_tool_contract"], "perms": [], "forbidden": []},
    {"id": "tool_b4_guardrails", "owner": "finalis/ai_employee/tool_guardrails.py", "classification": "governance_tool",
     "purpose": "TOOL-B4 Causal Pre-Action Reference Monitor + Counterfactual Denial Twin.",
     "paths": ["finalis/ai_employee/tool_guardrails.py", "finalis/ai_employee/tool_guardrails_store.py"],
     "routes": ["/ai-tools/actions"], "tables": ["ai_action_"], "perms": [], "forbidden": []},
    {"id": "tool_b5_broker", "owner": "finalis/ai_employee/tool_broker.py", "classification": "governance_tool",
     "purpose": "TOOL-B5 Four-Plane Proof-Carrying Null Broker.",
     "paths": ["finalis/ai_employee/tool_broker.py", "finalis/ai_employee/tool_broker_store.py"],
     "routes": ["/ai-tools/broker"], "tables": ["ai_broker_"], "perms": [], "forbidden": []},
    {"id": "tool_b6_runtime", "owner": "finalis/ai_employee/tool_runtime.py", "classification": "governance_tool",
     "purpose": "TOOL-B6 Verifiable Read-Path Runtime Microkernel + Output Provenance Bisimulation.",
     "paths": ["finalis/ai_employee/tool_runtime.py", "finalis/ai_employee/tool_runtime_store.py"],
     "routes": ["/ai-tools/runtime"], "tables": ["ai_runtime_"], "perms": [], "forbidden": []},
    {"id": "tool_b7_write_intent", "owner": "finalis/ai_employee/tool_write_intent.py", "classification": "governance_tool",
     "purpose": "TOOL-B7 Transaction-Escrow Write-Intent Draft Runtime + Semantic Rollback-Attack Fence.",
     "paths": ["finalis/ai_employee/tool_write_intent.py", "finalis/ai_employee/tool_write_intent_store.py"],
     "routes": ["/ai-tools/write-intents"], "tables": ["ai_write_intent_"], "perms": [], "forbidden": []},
    {"id": "tool_b8_commit_simulation", "owner": "finalis/ai_employee/tool_commit_simulation.py", "classification": "governance_tool",
     "purpose": "TOOL-B8 Machine-Checkable Pre-B9 Assurance Envelope + B9 authority firewall (sealed).",
     "paths": ["finalis/ai_employee/tool_commit_simulation.py", "finalis/ai_employee/tool_commit_simulation_store.py"],
     "routes": ["/ai-tools/commit-simulations"], "tables": ["ai_commit_simulation_"], "perms": [], "forbidden": []},
    {"id": "tool_b9_local_transaction", "owner": "finalis/ai_employee/tool_local_transaction.py", "classification": "governance_tool",
     "purpose": "TOOL-B9 Finalis Transaction Twin + Proof-of-Execution (inert outbox; no real effect).",
     "paths": ["finalis/ai_employee/tool_local_transaction.py", "finalis/ai_employee/tool_local_transaction_store.py"],
     "routes": ["/ai-tools/local-transactions"],
     "tables": ["ai_local_transactions", "ai_local_transaction_outcomes",
                "ai_local_transaction_state", "ai_local_transaction_events"],
     "perms": [], "forbidden": []},
    {"id": "tool_b91_recovery", "owner": "finalis/ai_employee/tool_local_recovery.py", "classification": "governance_tool",
     "purpose": "TOOL-B9.1 Recovery Safety Case + Chaos Sentinel + Proof-of-Recovery (local-only; no authority/effect).",
     "paths": ["finalis/ai_employee/tool_local_recovery.py", "finalis/ai_employee/tool_local_recovery_store.py"],
     "routes": [], "tables": ["ai_local_transaction_recovery_"], "perms": [], "forbidden": []},
    {"id": "tool_b92_observability", "owner": "finalis/ai_employee/tool_work_observability.py", "classification": "governance_tool",
     "purpose": "TOOL-B9.2 Governed Work Lineage Observatory — read-only; PoWO authorizes nothing.",
     "paths": ["finalis/ai_employee/tool_work_observability.py", "finalis/ai_employee/tool_work_observability_store.py"],
     "routes": [], "tables": ["ai_governed_work_runs", "ai_work_outcome_proofs", "ai_work_lineage_events"],
     "perms": [], "forbidden": []},

    # ---- Employee layer ----
    {"id": "emp_a1_work_inbox", "owner": "finalis/ai_employee/employee_work_inbox.py", "classification": "governance_employee",
     "purpose": "EMP-A1 Employee Work Inbox — R-FSAFEQ Governed Work Admission Fabric (admits + prepares fenced handoff; executes nothing).",
     "paths": ["finalis/ai_employee/employee_work_inbox.py", "finalis/ai_employee/employee_work_inbox_store.py"],
     "routes": ["/ai-employee/work-inbox", "/ai-employee"],
     "tables": ["ai_employee_work_"], "perms": [], "forbidden": []},
]

# Package __init__ for ai_employee is shared plumbing owned by the ladder root.
SHARED_MODULES = {
    "finalis.ai_employee": "core_a1_identity",
    "finalis.ai_employee.__init__": "core_a1_identity",
}
