"""Bitemporal, provenance-carrying evidence claims (SP0008 §evidence,
D-0008-18/19/22).

Every assertion the inventory makes about a surface is an EVIDENCE CLAIM that is:
grounded (it cites a real source location), bitemporal (valid_from/valid_to =
when the fact held; observed_at/superseded_at = when we recorded/retracted it),
and provenance-linked (a W3C PROV entity/activity/agent projection saying which
detector activity generated it from which source). Contradictory claims are
PRESERVED, never averaged or silently resolved (D-0008-22): the inventory keeps
both and flags the contradiction.

Bitemporality lets the inventory answer "what did we believe about this contract
on date D, and what was actually true then" without rewriting history.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Iterable

from .canon import hash_obj
from .model import (Finding, P1, P2, BITEMPORAL_KEYS, PROV_NODE_KINDS,
                    PROV_EDGE_KINDS, EVIDENCE_UNGROUNDED, BITEMPORAL_INCONSISTENT,
                    PROVENANCE_BROKEN, CONTRADICTION_PRESERVED)

# a fixed sentinel meaning "open interval / still valid" — deterministic, no now()
OPEN = "OPEN"


@dataclass(frozen=True)
class Claim:
    """One grounded, bitemporal evidence claim about a surface."""
    subject_id: str          # the surface (or edge) the claim is about
    predicate: str           # e.g. "has_method", "writes_table", "emits_event"
    value: Any
    source_path: str         # grounding location
    source_line: int
    detector: str            # the activity that generated it
    valid_from: str = "REPO_EPOCH"   # bitemporal (symbolic, deterministic)
    valid_to: str = OPEN
    observed_at: str = "INVENTORY_RUN"
    superseded_at: str = OPEN

    @property
    def claim_id(self) -> str:
        return "EV-" + hash_obj({
            "s": self.subject_id, "p": self.predicate, "v": self.value,
            "src": [self.source_path, self.source_line],
            "det": self.detector})[:20]

    def as_dict(self) -> dict:
        return {
            "claim_id": self.claim_id,
            "subject_id": self.subject_id,
            "predicate": self.predicate,
            "value": self.value,
            "source": {"path": self.source_path, "line": self.source_line},
            "detector": self.detector,
            "valid_from": self.valid_from, "valid_to": self.valid_to,
            "observed_at": self.observed_at, "superseded_at": self.superseded_at,
        }


def claims_for_surface(surface, observations) -> list[Claim]:
    """Build grounded claims for one surface from its raw observations."""
    out: list[Claim] = []
    for o in observations:
        for pred, val in sorted(o.shape.items()):
            out.append(Claim(
                subject_id=surface.surface_id, predicate=pred, value=val,
                source_path=o.evidence_path, source_line=o.evidence_line,
                detector=o.detector))
    return out


def validate_claim(claim: Claim) -> list[Finding]:
    """A claim must be grounded and bitemporally consistent (D-0008-18/19)."""
    out: list[Finding] = []
    if not claim.source_path or not isinstance(claim.source_line, int) \
            or claim.source_line < 0:
        out.append(Finding(
            EVIDENCE_UNGROUNDED, P1, claim.subject_id,
            "evidence claim is not grounded in a real source location",
            {"claim": claim.as_dict()}))
    # ordering: an interval that closes before it opens is inconsistent
    for a, b in (("valid_from", "valid_to"), ("observed_at", "superseded_at")):
        av, bv = getattr(claim, a), getattr(claim, b)
        if bv != OPEN and isinstance(av, str) and isinstance(bv, str) \
                and av != "REPO_EPOCH" and av != "INVENTORY_RUN" and bv < av:
            out.append(Finding(
                BITEMPORAL_INCONSISTENT, P1, claim.subject_id,
                f"bitemporal interval {a}={av!r} > {b}={bv!r}", {}))
    return out


# --- W3C PROV projection (entity / activity / agent) ------------------------
def prov_projection(claims: Iterable[Claim]) -> dict:
    """Project claims into a PROV graph: each claim is an ENTITY generated by a
    detector ACTIVITY attributed to the detector AGENT, derived from a source
    ENTITY (the file). Deterministic node/edge ordering."""
    nodes: dict[str, dict] = {}
    edges: list[dict] = []
    for c in claims:
        ent = c.claim_id
        act = f"ACT:{c.detector}"
        agent = f"AGENT:{c.detector}"
        src = f"SRC:{c.source_path}"
        nodes[ent] = {"id": ent, "kind": "ENTITY"}
        nodes[act] = {"id": act, "kind": "ACTIVITY"}
        nodes[agent] = {"id": agent, "kind": "AGENT"}
        nodes[src] = {"id": src, "kind": "ENTITY"}
        edges.append({"from": ent, "to": act, "kind": "WAS_GENERATED_BY"})
        edges.append({"from": act, "to": src, "kind": "USED"})
        edges.append({"from": ent, "to": agent, "kind": "WAS_ATTRIBUTED_TO"})
        edges.append({"from": ent, "to": src, "kind": "WAS_DERIVED_FROM"})
    return {
        "nodes": sorted(nodes.values(), key=lambda n: n["id"]),
        "edges": sorted({(e["from"], e["to"], e["kind"]) for e in edges}),
    }


def validate_provenance(graph: dict) -> list[Finding]:
    """Every edge must reference declared nodes and a known PROV edge kind."""
    out: list[Finding] = []
    ids = {n["id"] for n in graph.get("nodes", [])}
    for e in graph.get("edges", []):
        frm, to, kind = e if isinstance(e, (list, tuple)) else \
            (e["from"], e["to"], e["kind"])
        if kind not in PROV_EDGE_KINDS:
            out.append(Finding(PROVENANCE_BROKEN, P1, str(frm),
                               f"unknown PROV edge kind {kind!r}", {}))
        if frm not in ids or to not in ids:
            out.append(Finding(PROVENANCE_BROKEN, P1, str(frm),
                               "PROV edge references an undeclared node",
                               {"edge": [frm, to, kind]}))
    return out


# --- contradiction preservation (D-0008-22) ---------------------------------
def find_contradictions(claims: Iterable[Claim]) -> list[Finding]:
    """Two claims with the same subject+predicate but different values are a
    contradiction. Preserve both; emit a finding — never average or drop
    (non-compensatory, D-0008-22)."""
    out: list[Finding] = []
    by_key: dict = {}
    for c in claims:
        by_key.setdefault((c.subject_id, c.predicate), []).append(c)
    for (subj, pred), group in sorted(by_key.items()):
        values = {hash_obj(g.value): g.value for g in group}
        if len(values) > 1:
            out.append(Finding(
                CONTRADICTION_PRESERVED, P2, subj,
                f"detectors disagree on {pred!r}: {len(values)} distinct "
                "values preserved (not reconciled)",
                {"predicate": pred,
                 "values": [values[k] for k in sorted(values)]}))
    return out
